DELIVERY_DATA = {
    "BD99281733": {
        "status": "In Transit",
        "last_location": "Accra",
        "last_update": "2 days ago",
        "estimated_delivery": "Tomorrow",
        "delay_reason": "High volume at sorting facility",
    },
    "DL44729103": {
        "status": "Delivered",
        "last_location": "Doorstep, Kumasi",
        "last_update": "on time",
        "estimated_delivery": "Delivered",
        "delay_reason": None,
    },
    "EG55822019": {
        "status": "Out for Delivery",
        "last_location": "Takoradi",
        "last_update": "1 hour ago",
        "estimated_delivery": "Today",
        "delay_reason": None,
    },
    "GH77213400": {
        "status": "In Transit",
        "last_location": "Tema Port",
        "last_update": "4 hours ago",
        "estimated_delivery": "2 days",
        "delay_reason": "Customs inspection",
    },
    "KE10098277": {
        "status": "Delayed",
        "last_location": "Nairobi Distribution Center",
        "last_update": "Yesterday",
        "estimated_delivery": "3 days",
        "delay_reason": "Weather delay",
    },
    "NG22441155": {
        "status": "Delivered",
        "last_location": "Victoria Island, Lagos",
        "last_update": "2 days ago",
        "estimated_delivery": "Delivered",
        "delay_reason": None,
    },
    "ZA33990433": {
        "status": "In Transit",
        "last_location": "Johannesburg Hub",
        "last_update": "5 hours ago",
        "estimated_delivery": "4 days",
        "delay_reason": None,
    },
    "TZ45100221": {
        "status": "Out for Delivery",
        "last_location": "Dar es Salaam",
        "last_update": "30 minutes ago",
        "estimated_delivery": "Today",
        "delay_reason": None,
    },
    "UG99022188": {
        "status": "Delayed",
        "last_location": "Entebbe Sorting Facility",
        "last_update": "1 day ago",
        "estimated_delivery": "5 days",
        "delay_reason": "Vehicle maintenance",
    },
    "ZA55120466": {
        "status": "In Transit",
        "last_location": "Cape Town",
        "last_update": "Yesterday",
        "estimated_delivery": "3 days",
        "delay_reason": "High demand at local hub",
    },
}